version: '3'
services:
  mysqldb:
    image: javatechie01/capstone-project:2
    environment:
       MYSQL_ROOT_PASSWORD: a5@2K414*
       MYSQL_DATABASE: springjdbc
       MYSQL_ROOT_USER : root
       MYSQL_PASSWORD: a5@2K414*
    ports:
      - "3307:3306"
  springboot-docker-container:
    image: javatechie01/capstone-project:1
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/springjdbc?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "a5@2K414*"
    build:
      context: "./"
      dockerfile: "Dockerfile"
    depends_on:
      - mysqldb