version: "3"
services:
  server:
    build: .
    #restart: always
    image: springboot-app
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/springjdbc?autoReconnect=true&useSSL=false
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    networks:
      - springmysql-net
    restart: always
    ports: 
      - 3307:3306
    environment:
       MYSQL_ROOT_PASSWORD: a5@2K414*
       MYSQL_DATABASE: springjdbc
       MYSQL_ROOT_USER : root
       MYSQL_PASSWORD: a5@2K414*

networks:
  springmysql-net: