apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: springboot-docker-container
  name: springboot-docker-container
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: springboot-docker-container
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: springboot-docker-container
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: a5@2K414*
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysqldb:3307/springjdbc?autoReconnect=true&useSSL=false
            - name: SPRING_DATASOURCE_USERNAME
              value: root
          image: javatechie01/capstone-project:1
          name: springboot-docker-container
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
